baseurl: "/"
languageCode: "en-us"
title: "gobai's blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  posts: "/posts/:filename/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: About
      url: "about/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3
    - name: Subscribe
      url: "index.xml"

params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; [gobai](https://blog.gocn.top) 2021 -- {Year} | [Github](https://github.com/go-bai)"

markup:
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 2
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true